### ISSUE TITLE
JS 2 Dart

### ISSUE THREAD

**Issue by MikeMitterer** [asgerf/parsejs.dart#5]
Hi, have you tried to generate Dart code from AST?

**Comment by asgerf** [comment]
Partly. The [dartify](https://github.com/asgerf/dartify) experiment generates a Dart API for a JS library based on its AST and a heap snapshot extracted with [jsnap](https://github.com/asgerf/jsnap) (note: dartify is not working, don't use it). Jsnap helps eliminate the nasty meta-programming that often happens during start-up of JS libraries (to build class hierarchies, etc).

But generating code for method bodies for actually porting JS code to Dart: nope. Even with jsnap there to help it's just too hard to get out anything useful.
